### PR TITLE
Add GHA for linting Python

### PR DESCRIPTION
**Pull request by jbritt1**
Add very beginning stage of some CI with a basic Python linter

### CODE REVIEW

**Comment by jbritt1** [comment]
Already failing as one can see in the initial run of the action: https://github.com/sclem/discord_stock_ticker/actions/runs/1130731577

**Comment by jbritt1** [comment]
This pull request will also solve the first task in #5.

**Review by Danielelston — APPROVED** [review]
LGTM
image

**Comment by jbritt1** [comment]
Stale, closing. Inactive codeowner

**Pull request closed without merging**
